from pprint import pprint

from services.ai_narrative import (
    generate_ai_risk_narrative,
)


sample_vendor = {
    "vendor_id": "TEST-001",
    "vendor_name": "Demo Payment Services",
    "category": "Payment Processing",
    "final_risk_score": 92,
    "final_risk_level": "CRITICAL",
    "access_risk_score": 88,
    "breach_risk_score": 95,
    "compliance_risk_score": 76,
    "lifecycle_risk_score": 65,
    "risk_reasons": [
        "Recent high-severity security breach",
        "Read-write access to sensitive payment systems",
        "Vendor is currently under investigation",
        "Security assessment is overdue",
    ],
    "rule_overrides": [
        "Under-investigation critical-risk override",
    ],
    "recommendations": [
        "Restrict the vendor's access immediately.",
        "Begin an executive security review.",
        "Validate breach-notification obligations.",
    ],
    "framework_mappings": [
        "GDPR Article 33",
        "NIST SA-9",
        "SOX 404",
    ],
}


result = generate_ai_risk_narrative(sample_vendor)

print("\nAI narrative test result:\n")
pprint(result, sort_dicts=False)

print("\nGenerated by:", result.get("generated_by"))

if result.get("fallback_reason"):
    print("Fallback reason:", result["fallback_reason"])